/*
Copyright 2019 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/mattmoor/foo-binding/pkg/apis/bindings/v1alpha1"
	scheme "github.com/mattmoor/foo-binding/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// FooBindingsGetter has a method to return a FooBindingInterface.
// A group's client should implement this interface.
type FooBindingsGetter interface {
	FooBindings(namespace string) FooBindingInterface
}

// FooBindingInterface has methods to work with FooBinding resources.
type FooBindingInterface interface {
	Create(*v1alpha1.FooBinding) (*v1alpha1.FooBinding, error)
	Update(*v1alpha1.FooBinding) (*v1alpha1.FooBinding, error)
	UpdateStatus(*v1alpha1.FooBinding) (*v1alpha1.FooBinding, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.FooBinding, error)
	List(opts v1.ListOptions) (*v1alpha1.FooBindingList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.FooBinding, err error)
	FooBindingExpansion
}

// fooBindings implements FooBindingInterface
type fooBindings struct {
	client rest.Interface
	ns     string
}

// newFooBindings returns a FooBindings
func newFooBindings(c *BindingsV1alpha1Client, namespace string) *fooBindings {
	return &fooBindings{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the fooBinding, and returns the corresponding fooBinding object, and an error if there is any.
func (c *fooBindings) Get(name string, options v1.GetOptions) (result *v1alpha1.FooBinding, err error) {
	result = &v1alpha1.FooBinding{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("foobindings").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of FooBindings that match those selectors.
func (c *fooBindings) List(opts v1.ListOptions) (result *v1alpha1.FooBindingList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.FooBindingList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("foobindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested fooBindings.
func (c *fooBindings) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("foobindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a fooBinding and creates it.  Returns the server's representation of the fooBinding, and an error, if there is any.
func (c *fooBindings) Create(fooBinding *v1alpha1.FooBinding) (result *v1alpha1.FooBinding, err error) {
	result = &v1alpha1.FooBinding{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("foobindings").
		Body(fooBinding).
		Do().
		Into(result)
	return
}

// Update takes the representation of a fooBinding and updates it. Returns the server's representation of the fooBinding, and an error, if there is any.
func (c *fooBindings) Update(fooBinding *v1alpha1.FooBinding) (result *v1alpha1.FooBinding, err error) {
	result = &v1alpha1.FooBinding{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("foobindings").
		Name(fooBinding.Name).
		Body(fooBinding).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *fooBindings) UpdateStatus(fooBinding *v1alpha1.FooBinding) (result *v1alpha1.FooBinding, err error) {
	result = &v1alpha1.FooBinding{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("foobindings").
		Name(fooBinding.Name).
		SubResource("status").
		Body(fooBinding).
		Do().
		Into(result)
	return
}

// Delete takes name of the fooBinding and deletes it. Returns an error if one occurs.
func (c *fooBindings) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("foobindings").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *fooBindings) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("foobindings").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched fooBinding.
func (c *fooBindings) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.FooBinding, err error) {
	result = &v1alpha1.FooBinding{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("foobindings").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
